### ISSUE TITLE
Its showing insufficient funds even though i have balance in my wallet

### ISSUE THREAD

**Issue by B-hue-hoop** [turazashvili/Automatic-ETH-wallet-Balance-Transfer#3]
I am using the code  with rinkeby test eth, i have 0.4974 rinkeby eth but it shows insufficient funds,can you see whats wrong in this code 
`import threading
from tracemalloc import stop
from web3 import Web3
w3 = Web3(Web3.HTTPProvider("https://rinkeby.infura.io/v3/351a6d3507b141e49aa4dbe380057fd6"))
private_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
pub_key ="0xf159327c4b79D3315530022F0045E1A2dea549e2"

recipient_pub_key = "0xd81e7774E7818B86CA78C4531A10404E836f66E0"
def loop():
    while True:
        balance = w3.eth.get_balance(pub_key)
        print()
        print(balance)
        gasPrice = w3.toWei('5', 'Gwei')
        gasLimit = 10
        nonce = w3.eth.getTransactionCount(pub_key)
        tx = {
            'chainId': 4,
            'nonce': nonce,
            'to': recipient_pub_key,
            'value': balance-gasLimit*gasPrice,
            'gas': gasLimit,
            'gasPrice': gasPrice
        }

        try:
         if balance > 0:
            signed_tx = w3.eth.account.sign_transaction(tx, private_key)
            tx_hash = w3.eth.send_raw_transaction(signed_tx.rawTransaction)
            print(w3.toHex(tx_hash))
        except:
            print("insufficient funds")

threading.Thread(target=loop, daemon=True).start()
input('Press Enter to exit.')

the result comes like this 

497423141839802000
insufficient funds

**Comment by ProGamersxD** [comment]
https://discord.gg/3uxgCDYR9a
